### ISSUE TITLE
Siteup ansible playbook

### ISSUE THREAD

**Issue by Nasfat79** [Nasfat79/Siteup-ansible-playbook#1]
Here is an example Ansible playbook to set up a website:
```
---
- name: Set up website
  hosts: [your_host_or_group]
  become: true

  tasks:
  - name: Install Apache
    apt:
      name: apache2
      state: present

  - name: Start Apache
    service:
      name: apache2
      state: started
      enabled: yes

  - name: Copy website files
    copy:
      content: "<html><body>Hello World!</body></html>"
      dest: /var/www/html/index.html
      owner: www-data
      group: www-data
      mode: '0644'

  - name: Configure Apache virtual host
    template:
      src: templates/apache.conf.j2
      dest: /etc/apache2/sites-available/000-default.conf
      mode: '0644'
    notify: restart apache

  handlers:
  - name: restart apache
    service:
      name: apache2
      state: restarted
```
Let me explain what this playbook does:

- Installs Apache using the `apt` module.
- Starts Apache and enables it to start automatically on boot using the `service` module.
- Copies a simple HTML file to the website document root using the `copy` module.
- Configures an Apache virtual host using a template file (apache.conf.j2) and notifies the `restart apache` handler to restart Apache.

You'll need to create a `templates` directory alongside your playbook with the `apache.conf.j2` template file:
```
<VirtualHost *:80>
    ServerName {{ server_name }}
    DocumentRoot /var/www/html

    <Directory /var/www/html>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>
```
Replace `{{ server_name }}` with your server's domain name or IP address.

Run the playbook with `ansible-playbook -i <hosts_file> siteup.yml` (replace `<hosts_file>` with your Ansible inventory file).
![Ansible](https://github.com/Nasfat79/Siteup-ansible-playbook/assets/1535
![Ansible](https://github.com/Nasfat79/Siteup-ansible-playbook/assets/153554846/7a0d06c4-de5a-423a-b333-e5ae44f6068f)
